version: '3'
services:
  db:
    container_name: postgres
    image: postgres:11
    volumes:
      - ./backend/tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
  backend:
    container_name: backend
    build: .
    volumes:
      - ./backend/app:/myapp/backend/app
      - ./backend/config:/myapp/backend/config
      - ./backend/db:/myapp/backend/db
      - ./backend/lib:/myapp/backend/lib
      - ./backend/log:/myapp/backend/log
      - ./backend/test:/myapp/backend/test
      - ./backend/vendor:/myapp/backend/vendor
    depends_on:
      - db
    ports:
      - 3001:80
  frontend:
    container_name: frontend
    image: "node:14-alpine"
    user: "node"
    working_dir: /myapp/frontend
    volumes:
      - ./frontend:/myapp/frontend
    command: "yarn dev"
    depends_on:
      - backend
    ports:
      - 3000:3000
